version: '3'
service: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: postgres
      POSTGRES_DB: webBadminton
    app:
      image: badmintonApp
      port: 
        - 13000:3000